#spring.application.name=comments-project
spring:
  application:
    name: comments-project
  datasource:
    url: jdbc:mysql://localhost:3306/comment-section-app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Dani
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true


  sql:
    init:
      mode: always

server:
  port: 8081

