#spring.application.name=comments-project
spring:
  application:
    name: comments-project
  datasource:
    url: jdbc:mysql://localhost:3306/comment-section?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Dani
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

