spring:
  application:
    name: comments-project

  datasource:
    url: jdbc:postgresql://dpg-d00ifhidbo4c7393er6g-a:5432/capturethis_db
    username: capturethis_db_user
    password: aFtpyGiXukm14LLk354aL7rLhMgyYLKy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_schema: comments
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8081
