spring:
  application:
    name: comments-project

  datasource:
    url: jdbc:postgresql://localhost:5432/comment_section
    username: postgres
    password: your_password_here
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
